<a href="https://colab.research.google.com/github/juwoncozyboy/Machine_learning/blob/main/day05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
iphone_df = pd.read_csv('iphone.csv', encoding ='cp949')
#channal_df = pd.read_csv('channal.csv')
iphone_df = pd.read_csv('iphone.csv', index_col = 0)
iphone_df

                    release date  display memory relase version Face ID
iPhone 7              2016-09-16      4.7    2GB       iOS 10.0      No
iPhone 7 Plus         2016-09-16      5.5    3GB       iOS 10.0      No
iPhone 8              2017-09-22      4.7    2GB       iOS 11.0      No
iPhone 8 Plus         2017-09-22      5.5    3GB       iOS 11.0      No
iPhone X              2017-11-03      5.8    3GB       iOS 11.1     Yes
iPhone XS             2018-09-21      5.8    4GB       iOS 12.0     Yes
iPhone XS Max         2018-09-21      6.5    4GB       iOS 12.0     Yes
iPhone XR             2018-10-26      6.1    3GB       iOS 12.0     Yes
iPhone 11             2019-09-20      6.1    4GB       iOS 13.0     Yes
iPhone 11 Pro         2019-09-20      5.8    4GB       iOS 13.0     Yes
iPhone 11 Pro Max     2019-09-20      6.5    4GB       iOS 13.0     Yes
iPhone SE (2nd Gen)   2020-04-24      4.7    3GB       iOS 13.4     Yes
iPhone 12 Mini        2020-11-13      5.4    4GB       iOS 14.1     Yes
iPhone 12             2020-10-23      6.1    4GB       iOS 14.1     Yes
iPhone 12 Pro         2020-10-23      6.1    6GB       iOS 14.1     Yes
iPhone 12 Pro Max     2020-11-13      6.7    6GB       iOS 14.1     Yes
iPhone 13 Mini        2021-09-24      5.4    4GB         iOS 15     Yes
iPhone 13             2021-09-24      6.1    4GB         iOS 15     Yes
iPhone 13 Pro         2021-09-24      6.1    6GB         iOS 15     Yes
iPhone 13 Pro Max     2021-09-24      6.7    6GB         iOS 15     Yes
iPhone 14             2022-10-07      6.1    6GB     iOS 16.3.1     Yes

In [41]:
#iphone 14의 출시일, 메모리만 출력
ip14 = iphone_df.iloc[20:21]
ip14_db = ip14[['release date', 'memory']]
ip14_db = pd.DataFrame(ip14_db)
ip14_db
#iphone x 한 행을 출력
#ipx = iphone_df.iloc[5]
#ipx

          release date memory
iPhone 14   2022-10-07    6GB

In [70]:
i1 = iphone_df.loc['iPhone 14', 'release date']
i2 = iphone_df.loc['iPhone 14', 'memory']
print(i1,i2)

df = iphone_df.loc['iPhone 14']
df[['release date', 'memory']]

2022-10-07 6GB

release date    2022-10-07
memory                 6GB
Name: iPhone 14, dtype: object

In [71]:
#iphone x 한 행을 출력
ipx = iphone_df.iloc[4:5]
ipx = pd.DataFrame(ipx)
ipx

         release date  display memory relase version Face ID
iPhone X   2017-11-03      5.8    3GB       iOS 11.1     Yes

In [76]:
#loc를 이용해서 시리즈 출력
df = iphone_df.loc['iPhone X']
df

#loc를 이용해서 데이터 프레임으로 출력
df = iphone_df.loc[iphone_df.index == 'iPhone X']
df

         release date  display memory relase version Face ID
iPhone X   2017-11-03      5.8    3GB       iOS 11.1     Yes

In [75]:
#face id 를 지원하는 iphone 모델의 개수
print(len(iphone_df[iphone_df['Face ID']=='Yes']))

count = iphone_df[iphone_df['Face ID']=='Yes'].shape[0]
count

17

17

In [46]:
# ios14이상 버전을 지원하는 모델
iphone_df.info()
iphone_df[iphone_df['relase version']>='iOS 14']

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, iPhone 7 to iPhone 14
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   release date    21 non-null     object
 1   display         21 non-null     float64
 2   memory          21 non-null     object
 3   relase version  21 non-null     object
 4   Face ID         21 non-null     object
dtypes: float64(1), object(4)
memory usage: 1.5+ KB

                  release date  display memory relase version Face ID
iPhone 12 Mini      2020-11-13      5.4    4GB       iOS 14.1     Yes
iPhone 12           2020-10-23      6.1    4GB       iOS 14.1     Yes
iPhone 12 Pro       2020-10-23      6.1    6GB       iOS 14.1     Yes
iPhone 12 Pro Max   2020-11-13      6.7    6GB       iOS 14.1     Yes
iPhone 13 Mini      2021-09-24      5.4    4GB         iOS 15     Yes
iPhone 13           2021-09-24      6.1    4GB         iOS 15     Yes
iPhone 13 Pro       2021-09-24      6.1    6GB         iOS 15     Yes
iPhone 13 Pro Max   2021-09-24      6.7    6GB         iOS 15     Yes
iPhone 14           2022-10-07      6.1    6GB     iOS 16.3.1     Yes

In [83]:
#5.iphone 11 pro 까지의(포함) 출시일, 디스플레이 출력(새로운 데이터 프레임이용)
# iphone_df[(iphone_df.index < 'iPhone 11 Pro') & (iphone_df.index >= 'iPhone 7')]
df = iphone_df
df

#방법1) 슬라이싱
df = df.loc['iPhone 7': 'iPhone 11 Pro', ['release date', 'display']]
df

#방법2) isin 사용
models = ['iPhone 7', 'iPhone 7    Plus', 'iPhone 8', 'iPhone 8 Plus', 'iPhone X',
          'iPhone XS', 'iPhone XS Max','iPhone XR', 'iPhone 11', 'iPhone 11 Pro']
df = df[df.index.isin(models)][['release date', 'display']]
df

              release date  display
iPhone 7        2016-09-16      4.7
iPhone 8        2017-09-22      4.7
iPhone 8 Plus   2017-09-22      5.5
iPhone X        2017-11-03      5.8
iPhone XS       2018-09-21      5.8
iPhone XS Max   2018-09-21      6.5
iPhone XR       2018-10-26      6.1
iPhone 11       2019-09-20      6.1
iPhone 11 Pro   2019-09-20      5.8

##1) 람다함수

In [79]:
#람다함수(간단한 함수를 한줄의 코드로 정의하는 방법, 익명함수)
#함수명 = lambda 변수명 : 수식

add = lambda x, y : x + y
print(add(3, 5))

df = pd.DataFrame({'salary':[5000, 6000, 7000]})
df

df['bonus'] = df['salary'].apply(lambda salary : salary * 0.1 )
df

8

   salary  bonus
0    5000  500.0
1    6000  600.0
2    7000  700.0

##2) 맵함수

In [85]:
number = [1,2,3,4,5]

n = list(map(lambda x : x**2, number))
print(n)

[1, 4, 9, 16, 25]

##3)필터함수

In [88]:
number = [1,2,3,4,5,6,7,8,9]
#홀수만 추출
odd = list(filter(lambda x: x % 2 == 1, number))
print(odd)

[1, 3, 5, 7, 9]

##2. 데이터전처리 시 사용하는 메소드

In [89]:
import pandas as pd
import numpy as np

#데이터 임의로 넣기
data = {'이름' : ['홍길동', '강감찬', '신사임당', '이순신', '유관순'],
        '성별' : ['남', '남', '여', '남', '여'],
        '나이' : [15, 14, 25, 54, 17],
        '키' : [172.5, 180.2, 158.7, 165.5, 140.2],
        '몸무게' : [70.3, 82.1, 47.5, 71.2, 65.8],
        '학생여부' : [False, False, False, True, True]
        }

#데이터 프레임으로 변환
df = pd.DataFrame(data)
df

     이름 성별  나이      키   몸무게   학생여부
0   홍길동  남  15  172.5  70.3  False
1   강감찬  남  14  180.2  82.1  False
2  신사임당  여  25  158.7  47.5  False
3   이순신  남  54  165.5  71.2   True
4   유관순  여  17  140.2  65.8   True

##1) 데이터 읽기와 쓰기

In [100]:
import pandas as pd

#데이터프레임 csv 파일로 저장
#df.to_csv("test.csv")

#csv 파일 읽기
df = pd.read_csv('test.csv')
df
#  데이터 프레임 엑셀파일로 저장
#df.to_excel('test.xlsx')
#df = pd.read_excel('test.xlsx')
#df
#print(df, type(df))

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,이름,성별,나이,키,몸무게,학생여부
0,0,0,0,0,0,0,0,홍길동,남,15,172.5,70.3,False
1,1,1,1,1,1,1,1,강감찬,남,14,180.2,82.1,False
2,2,2,2,2,2,2,2,신사임당,여,25,158.7,47.5,False
3,3,3,3,3,3,3,3,이순신,남,54,165.5,71.2,True
4,4,4,4,4,4,4,4,유관순,여,17,140.2,65.8,True

##2) 데이터 탐색

In [102]:
import pandas as pd

#head() : 데이터프레임의 처음 5개행 출력
print(df.head())
#()안에 내가 출력하고 싶은 행의 수를 작성해도됨

#tail() : 데이터 프레임의 마지막 5개 행을 출력
print(df.tail(1))
#()안에 내가 출력하고 싶은 행의 수를 작성해도됨

#info() : 데이터 프레임의 기본 정보를 출력(행/열 수, 결측치 유무, dtype 등)
print(df.info())

# describe() : 데이터 프레임의 기술 통계 정보 출력
print(df.describe())

#shape : 데이터프레임의 행과 열의 개수 반환
print(df.shape) #tuple 형태로 행과 열이 출력됨
df

   Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  \
0             0             0             0             0             0
1             1             1             1             1             1
2             2             2             2             2             2
3             3             3             3             3             3
4             4             4             4             4             4

   Unnamed: 0.1  Unnamed: 0    이름 성별  나이      키   몸무게   학생여부
0             0           0   홍길동  남  15  172.5  70.3  False
1             1           1   강감찬  남  14  180.2  82.1  False
2             2           2  신사임당  여  25  158.7  47.5  False
3             3           3   이순신  남  54  165.5  71.2   True
4             4           4   유관순  여  17  140.2  65.8   True
   Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  \
4             4             4             4             4             4

   Unnamed: 0.1  Unnamed: 0   이름 성별  나이      키   몸무게  학생여부
4             4           4  유관순  여  17  140.2  65.8  True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.6  5 non-null      int64
 1   Unnamed: 0.5  5 non-null      int64
 2   Unnamed: 0.4  5 non-null      int64
 3   Unnamed: 0.3  5 non-null      int64
 4   Unnamed: 0.2  5 non-null      int64
 5   Unnamed: 0.1  5 non-null      int64
 6   Unnamed: 0    5 non-null      int64
 7   이름            5 non-null      object
 8   성별            5 non-null      object
 9   나이            5 non-null      int64
 10  키             5 non-null      float64
 11  몸무게           5 non-null      float64
 12  학생여부          5 non-null      bool
dtypes: bool(1), float64(2), int64(8), object(2)
memory usage: 613.0+ bytes
None
       Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  \
count      5.000000      5.000000      5.000000      5.000000      5.000000
mean       2.000000      2.000000      2.000000      2.000000      2.000000
std        1.581139      1.581139      1.581139      1.581139      1.581139
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        1.000000      1.000000      1.000000      1.000000      1.000000
50%        2.000000      2.000000      2.000000      2.000000      2.000000
75%        3.000000      3.000000      3.000000      3.000000      3.000000
max        4.000000      4.000000      4.000000      4.000000      4.000000

       Unnamed: 0.1  Unnamed: 0         나이           키       몸무게
count      5.000000    5.000000   5.000000    5.000000   5.00000
mean       2.000000    2.000000  25.000000  163.420000  67.38000
std        1.581139    1.581139  16.777962   15.246213  12.62446
min        0.000000    0.000000  14.000000  140.200000  47.50000
25%        1.000000    1.000000  15.000000  158.700000  65.80000
50%        2.000000    2.000000  17.000000  165.500000  70.30000
75%        3.000000    3.000000  25.000000  172.500000  71.20000
max        4.000000    4.000000  54.000000  180.200000  82.10000
(5, 13)

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,이름,성별,나이,키,몸무게,학생여부
0,0,0,0,0,0,0,0,홍길동,남,15,172.5,70.3,False
1,1,1,1,1,1,1,1,강감찬,남,14,180.2,82.1,False
2,2,2,2,2,2,2,2,신사임당,여,25,158.7,47.5,False
3,3,3,3,3,3,3,3,이순신,남,54,165.5,71.2,True
4,4,4,4,4,4,4,4,유관순,여,17,140.2,65.8,True

##3)데이터 선택과 필터링

In [111]:
import pandas as pd

#데이터 프레임 생성
data = {
    '이름' : ['짱구', '유리', '맹구', '철수', '훈이'],
    '국어' : [80, 90, 70, 85, 94],
    '영어' : [95, 92, 75, 80, 74],
    '수학' : [70, 77, 90, 85, 80],
    '과학' : [94, 88, 78, 65, 72]
    }

# print(data, type(data))
df = pd.DataFrame(data)
df

#loc : 라벨 기반으로 데이터프레임의 행과 열 선택
# 인덱스 라벨이 0인 행과 '국어', '영어'열 선택
#print(df.loc[0,['국어','영어']])

#인덱스 라벨이 1,2인 행과 '영어', '수학' 열 선택
#print(df.loc[[1,2],['영어','수학']])

#iloc : 정수형 위치인덱스 기반으로 데이터 프레임의 행과 열 선택
#첫번째 행과 1,2번째 열 선택
#print(df.iloc[0,1:3])

# 1, 3번째 행을 선택하고 2,4번째 열 선택
print(df.iloc[[1,3],[2,4]])
#국어 성적이 80점 또는 90점인 행 선택
print(df[df['국어'].isin([80,90])])

#query : 조건을 설정하여 데이터 필터링
#국어 성적이 80점 이상이고 수학 성적이 80점 이상인 행 선택
print(df.query("국어 >=80 and 수학 >=80"))

   영어  과학
1  92  88
3  80  65
   이름  국어  영어  수학  과학
0  짱구  80  95  70  94
1  유리  90  92  77  88
   이름  국어  영어  수학  과학
3  철수  85  80  85  65
4  훈이  94  74  80  72

In [140]:
data = {
    '이름' : ['짱구', '철수', '유리', '맹구', "짱아"],
    '성별' : ['남', '남', '여', '남', '여'],
    '나이' : [15, 14, 25, 10, 5],
    '키' : [150.1, 163.2, 100.2, 125.3, 80.3],
    '몸무게' : [40, 43, 34, 38, 23],
    '학생여부' : [True, True, False, True, False]
}

df = pd.DataFrame(data)
df

#"짱구", "유리"의 키와 몸무게 선택
#1~3행과 2~4열 선택
#성별 열에서 '여' 행 선택
#나이 열에서 15살 이상인 학생이 아닌 사람 선택

   이름 성별  나이      키  몸무게   학생여부
0  짱구  남  15  150.1   40   True
1  철수  남  14  163.2   43   True
2  유리  여  25  100.2   34  False
3  맹구  남  10  125.3   38   True
4  짱아  여   5   80.3   23  False

In [141]:
df[df['이름'].isin(['짱구', '유리'])][['이름', '키', '몸무게']]
df.query('이름 in ["짱구", "유리"]')[['이름', '키', '몸무게']]
#i1 = df.iloc[[0,2],[0,3,4]]
#i1

   이름      키  몸무게
0  짱구  150.1   40
2  유리  100.2   34

In [142]:
i2 = df.iloc[1:4,2:5]
i2

print(df.loc[1:3,'나이':'몸무게'])

   나이      키  몸무게
1  14  163.2   43
2  25  100.2   34
3  10  125.3   38

In [143]:
df[df['성별'].isin(['여'])]
#df[df['성별']=='여']

   이름 성별  나이      키  몸무게   학생여부
2  유리  여  25  100.2   34  False
4  짱아  여   5   80.3   23  False

In [144]:
df.query("나이 >=15 and 학생여부 == False")

   이름 성별  나이      키  몸무게   학생여부
2  유리  여  25  100.2   34  False

In [147]:
data = {
    '이름' : ['짱구', '철수', '유리', '맹구', "짱아"],
    '성별' : ['남', '남', '여', '남', '여'],
    '나이' : [15, 14, None, 10, 5],
    '키' : [150.1, 163.2, 100.2, None, 80.3],
    '몸무게' : [40, 43, 34, 38, None],
    '학생여부' : [True, True, False, None, False]
}

df = pd.DataFrame(data)
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   성별      5 non-null      object
 2   나이      4 non-null      float64
 3   키       4 non-null      float64
 4   몸무게     4 non-null      float64
 5   학생여부    4 non-null      object
dtypes: float64(3), object(3)
memory usage: 368.0+ bytes

   이름 성별    나이      키   몸무게   학생여부
0  짱구  남  15.0  150.1  40.0   True
1  철수  남  14.0  163.2  43.0   True
2  유리  여   NaN  100.2  34.0  False
3  맹구  남  10.0    NaN  38.0   None
4  짱아  여   5.0   80.3   NaN  False

In [148]:
#fillna(): 결측값을 특정 값으로 채움
df = df.fillna(0.0)
df

   이름 성별    나이      키   몸무게   학생여부
0  짱구  남  15.0  150.1  40.0   True
1  철수  남  14.0  163.2  43.0   True
2  유리  여   0.0  100.2  34.0  False
3  맹구  남  10.0    0.0  38.0    0.0
4  짱아  여   5.0   80.3   0.0  False

In [149]:
# groupby() : 열을 기준으로 데이터를 그룹화함
# 성별열을 기준으로 그룹화하여 키의 평균값을 구함
print(df.groupby(['성별'])[['키']].mean())

# sort_values() : 열의 값을 기준으로 데이터를 정렬함
# 나이열을 기준으로 오름차순 정렬
print(df.sort_values('나이')) #오름차순정렬
print(df.sort_values('나이', ascending = False)) #내림차순정렬

# rename() : 열 또는 행의 이름을 변경함
# 키 열의 이름을 Height로 변경
df.rename(columns={'키':'Height'}, inplace = True)
df

             키
성별
남   104.433333
여    90.250000
   이름 성별    나이      키   몸무게   학생여부
2  유리  여   0.0  100.2  34.0  False
4  짱아  여   5.0   80.3   0.0  False
3  맹구  남  10.0    0.0  38.0    0.0
1  철수  남  14.0  163.2  43.0   True
0  짱구  남  15.0  150.1  40.0   True
   이름 성별    나이      키   몸무게   학생여부
0  짱구  남  15.0  150.1  40.0   True
1  철수  남  14.0  163.2  43.0   True
3  맹구  남  10.0    0.0  38.0    0.0
4  짱아  여   5.0   80.3   0.0  False
2  유리  여   0.0  100.2  34.0  False

   이름 성별    나이  Height   몸무게   학생여부
0  짱구  남  15.0   150.1  40.0   True
1  철수  남  14.0   163.2  43.0   True
2  유리  여   0.0   100.2  34.0  False
3  맹구  남  10.0     0.0  38.0    0.0
4  짱아  여   5.0    80.3   0.0  False

In [165]:
data = {
    '이름' : ['짱구', '철수', '유리', '맹구', "짱아","짱아"],
    '성별' : ['남', '남', '여', '남', '여','여'],
    '나이' : [15, 14, None, 10, 5,5],
    '키' : [150.1, 163.2, 100.2, None, 80.3, 80.3],
    '몸무게' : [40, 43, 34, 38, None, None],
    '학생여부' : [True, True, False, None, False, False]
}

df = pd.DataFrame(data)

df

   이름 성별    나이      키   몸무게   학생여부
0  짱구  남  15.0  150.1  40.0   True
1  철수  남  14.0  163.2  43.0   True
2  유리  여   NaN  100.2  34.0  False
3  맹구  남  10.0    NaN  38.0   None
4  짱아  여   5.0   80.3   NaN  False
5  짱아  여   5.0   80.3   NaN  False

In [166]:
# drop_duplicates() : 중복된 행을 제거함
df = df.drop_duplicates()
df

# pivot() : 데이터 프레임의 열을 행 인덱스와 열로 반환함
# 이름 열을 행 인덱스로 변경
#df.pivot(index = '이름', columns = '성별', values = '나이')

# merge() : 두 개 이상의 데이터 프레임을 병합함
df2 = pd.DataFrame({'과목' : ['국어', '영어', '수학', '사회', '과학'],
                   '학점' : [4.5, 3.7, 3.9, 4.2, 4.4],
                    '이름' : ['짱구', '유리', '맹구', '짱아', '철수']})
df2

merge_df = pd.merge(df, df2, on = "이름")
merge_df

# apply() : 함수를 통해 데이터 프레임의 행 또는 열에 작업을 수행
# 키열과 몸무게 열의 평균값을 구하기
# print(merge_df[['키', '몸무게']].apply(np.mean))

# map() : 열의 각 요소에 함수나 매핑 딕셔너리를 적용하여 값을 변환함
# 성별열의 값을 1로 변환함
#df['성별']
#df.info()
df['성별'] = df['성별'].map({'남': 1, '여': 0})
print(df.info())
print(df)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   성별      5 non-null      int64
 2   나이      4 non-null      float64
 3   키       4 non-null      float64
 4   몸무게     4 non-null      float64
 5   학생여부    4 non-null      object
dtypes: float64(3), int64(1), object(2)
memory usage: 280.0+ bytes
None
   이름  성별    나이      키   몸무게   학생여부
0  짱구   1  15.0  150.1  40.0   True
1  철수   1  14.0  163.2  43.0   True
2  유리   0   NaN  100.2  34.0  False
3  맹구   1  10.0    NaN  38.0   None
4  짱아   0   5.0   80.3   NaN  False

<ipython-input-166-3689c67fde09>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['성별'] = df['성별'].map({'남': 1, '여': 0})

In [168]:
data = {
    '이름' : ['짱구', '철수', '유리', '맹구', "짱아", "짱아"],
    '성별' : ['남', np.nan, '여', '남', '여', '여'],
    '나이' : [15, 14, None, 10, 5, 5],
    '키' : [150.1, 163.2, 100.2, None, 80.3, 80.3],
    '몸무게' : [40, 43, 34, 38, None, None],
    '학생여부' : [True, True, False, None, False, False]
}
#np.nan : NaN 값을 나타내는 Numpy 함수

df = pd.DataFrame(data)
#Nan값을 2로 대체
df['성별'] = df['성별'].fillna(2)

#성별열의 값을 남 : 1과 여 : 0으로 변환
df['성별'] = df['성별'].map({2:2, '남':1, '여':0})

df

   이름  성별    나이      키   몸무게   학생여부
0  짱구   1  15.0  150.1  40.0   True
1  철수   2  14.0  163.2  43.0   True
2  유리   0   NaN  100.2  34.0  False
3  맹구   1  10.0    NaN  38.0   None
4  짱아   0   5.0   80.3   NaN  False
5  짱아   0   5.0   80.3   NaN  False

In [171]:
# astype(): 열의 데이터 타입을 변경함
# "나이열의 데이터타입을 문자열로 변경"
df['나이'] = df['나이'].astype(str)
df.info()

#나이 열의 타입 확인
print(df['나이'].dtype) #데이터프레임, 시리즈 데이터 타입 확인

# agg() : 그룹화된 데이터에 대해 집계함수를 적용(sum, mean, max 등)
#print(df.groupby('이름'))[['나이','키','몸무게']].agg()
#fillna()-> 0.0변경 후 나이, 키, 몸무게의 평균값 구하기
df.fillna(0.0, inplace = True)

#이름을 기준으로 나이, 키 , 몸무게의 평균 구하기
avg = df.groupby('이름')[['키', '몸무게']].agg(np.mean)
avg

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      6 non-null      object
 1   성별      6 non-null      int64
 2   나이      6 non-null      object
 3   키       5 non-null      float64
 4   몸무게     4 non-null      float64
 5   학생여부    5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 416.0+ bytes
object