<a href="https://colab.research.google.com/github/juwoncozyboy/Machine_learning/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 판다스

##2 시리즈(Series)

In [158]:
import pandas as pd
di_data = {'서울':1, '경기':2, '강원':3}
li_data = ['20230723', 723, 'python', 100, True]

#시리즈로 변경
s1 = pd.Series(di_data)
s2 = pd.Series(li_data)

print(s1)
print(s2)

서울    1
경기    2
강원    3
dtype: int64
0    20230723
1         723
2      python
3         100
4        True
dtype: object

In [159]:
print(s1)

#추가
s1['부산'] = 4
print(s1)
#s1.append(pd.Series(['제주'])) append 메소드로 ['값'] 값이 추가

#수정
s1['서울'] = 10
print(s1)

s1 = s1.drop('강원')
print(s1)

서울    1
경기    2
강원    3
dtype: int64
서울    1
경기    2
강원    3
부산    4
dtype: int64
서울    10
경기     2
강원     3
부산     4
dtype: int64
서울    10
경기     2
부산     4
dtype: int64

In [160]:
print(s2)

# 인덱스 5에 해당하는 위치에 값을 추가
s2[5] = 100
print(s2)

# 인덱스 2에 해당하는 값을 pandas로 수정
s2[2] = 'Pandas'
print(s2)
s2.at[0] = 20230724
print(s2)

#5번째 값 삭제
s2 = s2.drop(5)
print(s2)

0    20230723
1         723
2      python
3         100
4        True
dtype: object
0    20230723
1         723
2      python
3         100
4        True
5         100
dtype: object
0    20230723
1         723
2      Pandas
3         100
4        True
5         100
dtype: object
0    20230724
1         723
2      Pandas
3         100
4        True
5         100
dtype: object
0    20230724
1         723
2      Pandas
3         100
4        True
dtype: object

In [161]:
#데이터 자료형
#int, float형이 섞이면 float로 변환됨
# s = pd.Series([1, 2, 3, 4.1, 5.5])
# print(s)

# for i in s:
#     print(type(i))

#여러가지 자료형이 있으면 object
# s = pd.Series([1, '2', True, 5.0])
# print(s)

# for i in s:
#     print(type(i))

#직접 데이터 타입을 명시해주면 string으로 나옴
s = pd.Series([1, 2, 3], dtype = 'string')
print(s)

#astype() 원본에 영향을 주지 않음(다시 저장해서 나옴)
s = s.astype('int')
print(s)

0    1
1    2
2    3
dtype: string
0    1
1    2
2    3
dtype: int64

In [162]:
import pandas as pd

values = [[1,2,3], [4,5,6], [7,8,9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']
df = pd.DataFrame(values, index = index, columns = columns)
print(df)
df

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

##1) 딕셔너리 -> 데이터프레임

In [163]:
student = {'name':['짱구', '철수', '맹구', '훈이'], 'score':[50, 95, 25, 60]}
print(student, type(student))

df = pd.DataFrame(student, index = ['학생1', '학생2', '학생3', '학생4'])
df

{'name': ['짱구', '철수', '맹구', '훈이'], 'score': [50, 95, 25, 60]} <class 'dict'>

    name  score
학생1   짱구     50
학생2   철수     95
학생3   맹구     25
학생4   훈이     60

##2) 리스트 -> 데이터프레임

In [164]:
value = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index = index, columns = columns)
df

#인데스 변경
new_index = ['일', '이', '삼']
print(df.index)
df.index = new_index
df

#컬럼 변경
print(df.columns)
new_columns = ['a', 'b', 'c']
df.columns = new_columns
df

Index(['one', 'two', 'three'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

   a  b  c
일  1  2  3
이  4  5  6
삼  7  8  9

In [165]:
data_li = [['1000','짱구', 50], ['1001', '철수', 98],['1002', '훈이', 82],['1003', '맹구',63]]
print(data_li,type(data_li))

df = pd.DataFrame(data_li)
print(df)
print(df.index)
print(df.columns)
df

df = pd.DataFrame(data_li, columns = ['학번', '이름', '정수'])
print(df.columns)
df

[['1000', '짱구', 50], ['1001', '철수', 98], ['1002', '훈이', 82], ['1003', '맹구', 63]] <class 'list'>
      0   1   2
0  1000  짱구  50
1  1001  철수  98
2  1002  훈이  82
3  1003  맹구  63
RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)
Index(['학번', '이름', '정수'], dtype='object')

     학번  이름  정수
0  1000  짱구  50
1  1001  철수  98
2  1002  훈이  82
3  1003  맹구  63

##3) 데이터프레임 -> 딕셔너리

In [166]:
data = pd.DataFrame(data_li, columns = ['학번', '이름', '정수'], index = ['학생1', '학생2', '학생3', '학생4'])
df

     학번  이름  정수
0  1000  짱구  50
1  1001  철수  98
2  1002  훈이  82
3  1003  맹구  63

In [167]:
#열이름은 키로 변환, 각 레코드는 값으로 변환, 각 인덱스는 키로 변환
df.to_dict()

# 열이름은 키로 변환, 각 쌍은 각각의 목록으로 변환
df.to_dict('list')

#인덱스는 키로 변환, 각 레코드는 값으로 변환, 열이름은 키로 변환
df.to_dict('index')

#각 행을 딕셔너리로 변환
df.to_dict('records')

[{'학번': '1000', '이름': '짱구', '정수': 50},
 {'학번': '1001', '이름': '철수', '정수': 98},
 {'학번': '1002', '이름': '훈이', '정수': 82},
 {'학번': '1003', '이름': '맹구', '정수': 63}]

In [168]:
# 데이터프레임을 리스트로 변환
df.values.tolist()
df.columns.tolist()
#컬럼과 값을 함께 리스트로 변환
item_list = df.columns.tolist() + df.values.tolist()
print(item_list)

#특정 값만 리스트로 변환
item_list = df['이름'].values.tolist()
print(item_list)

['학번', '이름', '정수', ['1000', '짱구', 50], ['1001', '철수', 98], ['1002', '훈이', 82], ['1003', '맹구', 63]]
['짱구', '철수', '훈이', '맹구']

##5) 데이터프레임 수정 추가 삭제

In [169]:
data = {'name':['짱구', '철수', '맹구', '유리', '짱아'],
        'age' : [5, 5, 6, 6, '3'],
        'gender' : ['M', 'M', 'M', 'F', 'F']}
df = pd.DataFrame(data)
df

  name age gender
0   짱구   5      M
1   철수   5      M
2   맹구   6      M
3   유리   6      F
4   짱아   3      F

In [170]:
#열이름 변경 : name을 이름으로 변경
df.rename(columns ={'name':'이름'},inplace = True)
df

df.rename(columns ={0:'pr1'},inplace = True)
df

   이름 age gender
0  짱구   5      M
1  철수   5      M
2  맹구   6      M
3  유리   6      F
4  짱아   3      F

In [171]:
#추가
df['성적'] = [50,23,64,10,43]
df

   이름 age gender  성적
0  짱구   5      M  50
1  철수   5      M  23
2  맹구   6      M  64
3  유리   6      F  10
4  짱아   3      F  43

In [172]:
#삭제(drop() axis inplace)
#행삭제
#df.drop(1,inplace=True)
df

#열삭제
#df.drop('gender',axis=1,inplace=True)
df.drop('성적',axis = 'columns',inplace=True)

In [173]:
data = {'name':['짱구', '철수', '맹구', '유리', '짱아'],
        'age' : [5, 5, 6, 6, '3'],
        'gender' : ['M', 'M', 'M', 'F', 'F']}
df = pd.DataFrame(data)
df

  name age gender
0   짱구   5      M
1   철수   5      M
2   맹구   6      M
3   유리   6      F
4   짱아   3      F

In [174]:
#인덱스 라벨을 사용하여 특정 행 선택(loc이용)
select_row = df.loc[0]
print(select_row, type(select_row))

#인덱스 라벨을 사용하여 특정 행과 열 선택
select_r_c = df.loc[0, 'name']
print(select_r_c, type(select_r_c)) #str
select_r_c = df.loc[0, 'name':'age']
print(select_r_c, type(select_r_c)) #Series

df

name      짱구
age        5
gender     M
Name: 0, dtype: object <class 'pandas.core.series.Series'>
짱구 <class 'str'>
name    짱구
age      5
Name: 0, dtype: object <class 'pandas.core.series.Series'>

  name age gender
0   짱구   5      M
1   철수   5      M
2   맹구   6      M
3   유리   6      F
4   짱아   3      F

In [175]:
#iloc사용

select_row = df.iloc[0]
print(select_row)

#정수형 위치 인덱스를 사용하여 특정 행과 특정 열 선택
select_row_c = df.iloc[1, 0]
print(select_row_c)
select_row_c = df.iloc[1, 0:2]
print(select_row_c)

df

name      짱구
age        5
gender     M
Name: 0, dtype: object
철수
name    철수
age      5
Name: 1, dtype: object

  name age gender
0   짱구   5      M
1   철수   5      M
2   맹구   6      M
3   유리   6      F
4   짱아   3      F

##7) 열선택

In [176]:
#df['column_name'] 특정 열 데이터 선택 : 해당 열을 시리즈 객체로 반환
print(df['gender'])
print(df['age'])

#데이터 프레임으로 반환
df1 = df[['name']]
df1

0    M
1    M
2    M
3    F
4    F
Name: gender, dtype: object
0    5
1    5
2    6
3    6
4    3
Name: age, dtype: object

  name
0   짱구
1   철수
2   맹구
3   유리
4   짱아

In [177]:
#name열의 열 번호를 알아내기 위해 데이터 프레임의 columns 속성을 사용
column_name = df.columns.get_loc('name')
print(column_name)

#name열을 선택
select_name = df.iloc[:,0]
print(select_name)

0
0    짱구
1    철수
2    맹구
3    유리
4    짱아
Name: name, dtype: object

In [178]:
#loc를 이용한 열선택
#name 열 선택
select_name = df.loc[:,'name']
print(select_name)

0    짱구
1    철수
2    맹구
3    유리
4    짱아
Name: name, dtype: object

In [179]:
#<실습>
#1. 4개의 도시(city)와 해당 도시의 인구(population) 데이터를 가지고 있는 딕셔너리를
#사용하여 데이터 프레임과 시리즈 생성하기
cities = {'city':['서울', '부산', '인천', '대구'], 'population':[50256, 19800, 3000, 4000]}
print(cities, type(cities))


#시리즈와 데이터프레임 각각 출력
s = pd.Series(cities['population'], index = cities['city'], name = 'city')
print(s)
df = pd.DataFrame(cities)
df

{'city': ['서울', '부산', '인천', '대구'], 'population': [50256, 19800, 3000, 4000]} <class 'dict'>
서울    50256
부산    19800
인천     3000
대구     4000
Name: city, dtype: int64

  city  population
0   서울       50256
1   부산       19800
2   인천        3000
3   대구        4000

In [180]:
#2. 시리즈의 인덱스를 'A','B','C','D'로 바꾸기
s.index = ['A', 'B', 'C', 'D']
print(s)

#3. 데이터프레임에 'E'라는 도시와 해당 도시의 인구 데이터 추가하기(loc 사용)
df.loc['E'] = ['E', 50000]
df

#4. 시리즈의 평균 인구 구하기
s_mean = s.mean()
print(s_mean)

#5. 데이터 프레임에서 추가한 행 삭제하기(city가 'E'인 행 삭제)
df.drop('E', inplace = True)
df

#6. 'city'열을 선택해서 출력하기(loc사용)
city_column = df.loc[:, 'city']
print(city_column)

A    50256
B    19800
C     3000
D     4000
Name: city, dtype: int64
19264.0
0    서울
1    부산
2    인천
3    대구
Name: city, dtype: object

##8) 열 변환

In [181]:
data = {'이름':['짱구','철수','훈이','맹구','유리'],
        '나이':[5,5,6,6,5],
        '점수' :[100,90,45,50,70],
        '지역':['서울','부산','서울','대전','대구']}
df = pd.DataFrame(data)
df

df1 = df.transpose()
df1

df = df1.T
print(df)

   이름 나이   점수  지역
0  짱구  5  100  서울
1  철수  5   90  부산
2  훈이  6   45  서울
3  맹구  6   50  대전
4  유리  5   70  대구

##9) 추가적인 부분

In [182]:

#합계
print("점수의 합계 출력 : ",df['점수'].sum())

#평균
print("평균 출력 :", df['점수'].mean())
#파이썬에는 mean()없어서 len()를 이용해서 사용
li = [10,35,75,45]
print("평균 : ", sum(li)/len(li))

#정렬
#오름차순 정렬
print(df.sort_values(by='나이'))
#내림차순 정렬
print(df.sort_values(by='점수', ascending=False))

#데이터프레임 정보 출력
print(df.info())
#상위 5개 행 출력
print(df.head())
#하위 5개 행 출력
print(df.tail())

#조건식
#점수가 50점 미만인 행만 출력
print(df[df['점수']<50])
#지역이 서울인 행만 출력
print(df[df['지역'] == '서울'])
rows = df[(df['지역']=='서울')]
rows = df[(df['점수']>=60)]
rows = df[(df['지역']=='서울') & (df['점수']>=60)]

#슬라이싱
print(df.loc[1:3, '이름':'지역'])
print(df.iloc[1:4, 0:3])

점수의 합계 출력 :  355
평균 출력 : 71.0
평균 :  41.25
   이름 나이   점수  지역
0  짱구  5  100  서울
1  철수  5   90  부산
4  유리  5   70  대구
2  훈이  6   45  서울
3  맹구  6   50  대전
   이름 나이   점수  지역
0  짱구  5  100  서울
1  철수  5   90  부산
4  유리  5   70  대구
3  맹구  6   50  대전
2  훈이  6   45  서울
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   나이      5 non-null      object
 2   점수      5 non-null      object
 3   지역      5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes
None
   이름 나이   점수  지역
0  짱구  5  100  서울
1  철수  5   90  부산
2  훈이  6   45  서울
3  맹구  6   50  대전
4  유리  5   70  대구
   이름 나이   점수  지역
0  짱구  5  100  서울
1  철수  5   90  부산
2  훈이  6   45  서울
3  맹구  6   50  대전
4  유리  5   70  대구
   이름 나이  점수  지역
2  훈이  6  45  서울
   이름 나이   점수  지역
0  짱구  5  100  서울
2  훈이  6   45  서울
   이름 나이  점수  지역
1  철수  5  90  부산
2  훈이  6  45  서울
3  맹구  6  50  대전
   이름 나이  점수
1  철수  5  90
2  훈이  6  45
3  맹구  6  50